# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieMVVMArch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieMVVMArch
  pod 'AlamofireImage', '~> 4.1'
  pod 'Alamofire'

  target 'MovieMVVMArchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieMVVMArchUITests' do
    # Pods for testing
  end

end
